version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst

formatters:
  enable:
    - gofmt

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3

run:
  timeout: 5m

issues:
  exclude-use-default: false
